name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "1 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: raptazure/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 400bcd69e4d175936831c30987761a6b
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
